package com.amazonaws.lambda.awslambdatest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="ExampleTable")
public class Learning {
	
	@DynamoDBHashKey(attributeName="ID")
	//@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute(attributeName="NAME")
	private String name;
	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
	@DynamoDBAttribute(attributeName="CREATED_DATE")
	private String createdDate;
	@DynamoDBAttribute(attributeName="ROW_COUNTER")
	private Long rowCounter;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public Long getRowCounter() {
		return rowCounter;
	}
	public void setRowCounter(Long rowCounter) {
		this.rowCounter = rowCounter;
	}
	@Override
	public String toString() {
		return "Learning [id=" + id + ", name=" + name + ", createdDate=" + createdDate + "]";
	}
}
